# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackessex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='hide_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
