# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackessex', '0003_auto_20170429_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
